/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_khpcc_ilnitsky_courseproject_JavaAsm */

#ifndef _Included_ua_khpcc_ilnitsky_courseproject_JavaAsm
#define _Included_ua_khpcc_ilnitsky_courseproject_JavaAsm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_khpcc_ilnitsky_courseproject_JavaAsm
 * Method:    asmFAdd
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ua_khpcc_ilnitsky_courseproject_JavaAsm_asmFAdd
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     ua_khpcc_ilnitsky_courseproject_JavaAsm
 * Method:    asmFMul
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ua_khpcc_ilnitsky_courseproject_JavaAsm_asmFMul
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     ua_khpcc_ilnitsky_courseproject_JavaAsm
 * Method:    asmFDiv
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ua_khpcc_ilnitsky_courseproject_JavaAsm_asmFDiv
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
