/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_khpcc_ilnitsky_courseproject_JavaAsm */

#ifndef _Included_ua_khpcc_ilnitsky_courseproject_JavaAsm
#define _Included_ua_khpcc_ilnitsky_courseproject_JavaAsm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_khpcc_ilnitsky_courseproject_JavaAsm
 * Method:    asmAdd
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ua_khpcc_ilnitsky_courseproject_JavaAsm_asmAdd
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     ua_khpcc_ilnitsky_courseproject_JavaAsm
 * Method:    asmMul
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ua_khpcc_ilnitsky_courseproject_JavaAsm_asmMul
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     ua_khpcc_ilnitsky_courseproject_JavaAsm
 * Method:    asmDiv
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ua_khpcc_ilnitsky_courseproject_JavaAsm_asmDiv
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
