/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_khpcc_ilnitsky_javaasm_JavaAsm */

#ifndef _Included_ua_khpcc_ilnitsky_javaasm_JavaAsm
#define _Included_ua_khpcc_ilnitsky_javaasm_JavaAsm
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     ua_khpcc_ilnitsky_javaasm_JavaAsm
 * Method:    asmAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ua_khpcc_ilnitsky_javaasm_JavaAsm_asmAdd
  (JNIEnv *, jclass, jint, jint);
  
/*
 * Class:     ua_khpcc_ilnitsky_javaasm_JavaAsm
 * Method:    asmDiv
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ua_khpcc_ilnitsky_javaasm_JavaAsm_asmDiv
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
